
branches:
  # whitelist
  only:
    - wjt
  except:
    - master



enviroment:
  image: Visual Studio 2017
  image: Visual Studio 2015
  matrix:
    - QTDIR: C:\Qt\5.11.1\msvc2017_64

configuration:
  - release


